version: '2'

services:
  bitcoin-cli:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BINARIES_URL: <some_gitlab_or_github_location>
        ACCESS_TOKEN: PRIVATE-TOKEN
    command: bitcoin-cli -testnet -rpcuser=local -rpcpassword=local
    volumes:
      - <path/to/and/including/.bitcoin>:/monero
    stdin_open: true
    tty: true
    environment:
      - USER_ID=1000
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
